language: ruby
rvm:
    - 2.1

branches:
    only:
        - master
env:
    secure: "YkS9JVirAb+UbGkIVn5Bb0WnkmQSvbyg54TUnz8V8nOtVdz2dlpCXLlM/a8uCwqxJ4C41nv5CRqgmtOU3uo89F91ec/Whyemm3RdBFjCSNkdWBkuZNwVGwDEUwfBZ31IJh1nLP4ivBj/GJEh71/yLTSZ9DFf3H0etLNAz+JgZmMZdKk9RNcIo7S9dxwbjoAbIqTWS0H+f3pHTRJdso2W56ujtuyJe9ktIG/10xQOQl5vGKkq5L+thAX4laWVzm2Kf0YIPomUXGwm+aS/skT4Z32fEwowd2F9jntu5hf+xIg6KnZKTldBpGSbxr8OQBppfwvF2zSkt/SvnntrSwEq0qKzgh/f1Rb46BziEmb9Dpqcnenp0HnTZKzICZEuFfwmIvhA33U25jS0KixAvo+ZJaVPM2hSNC1N+DymSHCEaBofjU0ye6yAGMFJP7XUeOnJOHm+8aPj0E2WB2ODdsX8dfVYgjUJ1yjFbFU2Am55JCU8VGKdE5C3oqyTd+IAA8ysuQNR/PjzQCWIylz1DxWWv4JgAf35PFsqPhSjM6Pb7VdSHz9kLlAYW8UGOByN/6vn03Br8YWNCyGNFuiTpUxl4jb35octb+LveDwBb7A8yI4axoJiSgFUzUHYZNZaIEZIrsrs7ZlJ7XxA3Ho5/KCfP/ysB5ecRoFuilVszMJx4aw="

script: bundle exec rake travis

notifications:
  irc: "chat.freenode.net#ndsuacm"
