destination: _deploy


defaults:
    -
        scope:
            path: "" #applies to all files in the project (not limited by path)
            type: "posts" #applied to posts only
        values:
            layout: "posts"

    -
        scope:
            path: "" 
            type: "pages"
        values:
            layout: "default"

include: [".htaccess"]
exclude: [vendor]

kramdown:
  input: GFM
