# Site settings
title: NDSU ACM
url: http://ndacm.org
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#45693C'
  links: '#fff'

# Footer settings
footer: NDSU Association for Computing Machinery

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/acm-ndsu

# Build settings
markdown: kramdown
permalink: pretty
